on:
  push:
    branches:
      - main
      - test
      - test2
    paths:
      - 'src/test.yaml'

jobs:
  test_workflow:
    name: test workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate pattern
        run: |
          echo "AUTOTRAIN_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
          echo "PATTERN=output-${AUTOTRAIN_TIME}_${{ github.sha }}" >> $GITHUB_ENV
      - name: Print pattern
        run: |
          echo $PATTERN
          
