on:
  push:
    branches:
      - main
      - test
      - test2
    paths:
      - 'src/test.yaml'

jobs:
  test_workflow:
    name: test workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current time
        run: |
          echo "AUTOTRAIN_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: Print date
        run: |
          echo output-$AUTOTRAIN_TIME
          echo ${{ github.sha }}
